name: h-line

services:
  h-line:
    build:
      context: .
      dockerfile: Dockerfile
    image: flet_h-line:${APP_VERSION}
    pull_policy: missing
    container_name: flet_h-line_app
    restart: always
    env_file:
      - src/assets/.env
    volumes:
      - ./docker_data/output:/app/src/assets/output
      - ./docker_data/templates:/app/src/assets/templates
      - ./docker_data/locales:/app/src/assets/locales
    ports:
      - "8081:8000"
