name: h-line

services:
  h-line:
    build:
      context: .
      dockerfile: Dockerfile
    image: flet_h-line:latest
    pull_policy: build
    container_name: flet_h-line_app
    restart: always
    env_file:
      - src/assets/.env
    volumes:
      - ./docker_data/output:/app/src/assets/output
      - ./docker_data/templates:/app/src/assets/templates
    ports:
      - "8081:8080"
